












































 98%|█████████████████████████████████████████████████████████████████████████████████▏ | 44/45 [06:36<00:09,  9.11s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 45/45 [06:39<00:00,  7.34s/it]
Training completed. Do not forget to share your model on huggingface.co/models =)
100%|███████████████████████████████████████████████████████████████████████████████████| 45/45 [06:39<00:00,  8.87s/it]
Saving model checkpoint to ./output/Location
Configuration saved in ./output/Location/config.json
Model weights saved in ./output/Location/pytorch_model.bin
tokenizer config file saved in ./output/Location/tokenizer_config.json
Special tokens file saved in ./output/Location/special_tokens_map.json
07/20/2021 20:27:29 - INFO - __main__ -   *** Evaluate ***
***** Running Evaluation *****
  Num examples = 0
  Batch size = 8
07/20/2021 20:27:29 - INFO - __main__ -   ***** Eval results *****
07/20/2021 20:27:29 - INFO - __main__ -     eval_runtime = 0.0017
07/20/2021 20:27:29 - INFO - __main__ -     eval_samples_per_second = 0.0
07/20/2021 20:27:29 - INFO - __main__ -     eval_steps_per_second = 0.0
07/20/2021 20:27:29 - INFO - __main__ -     epoch = 3.0
07/20/2021 20:27:29 - INFO - filelock -   Lock 140490462336240 acquired on ../datasets/NER/Location/cached_test_BertTokenizer_192.lock
07/20/2021 20:27:29 - INFO - utils_ner -   Loading features from cached file ../datasets/NER/Location/cached_test_BertTokenizer_192
07/20/2021 20:27:29 - INFO - filelock -   Lock 140490462336240 released on ../datasets/NER/Location/cached_test_BertTokenizer_192.lock
***** Running Prediction *****
  Num examples = 0
  Batch size = 8
Traceback (most recent call last):
  File "run_ner.py", line 328, in <module>
    main()
  File "run_ner.py", line 283, in main
    preds_list, _ = align_predictions(predictions, label_ids)
  File "run_ner.py", line 208, in align_predictions
    preds = np.argmax(predictions, axis=1)
  File "<__array_function__ internals>", line 5, in argmax
  File "/work/wzkariampuzha/env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/work/wzkariampuzha/env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/work/wzkariampuzha/env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1